### ISSUE TITLE
gtk2/ddb_infobar_gtk2.so] Error 1

### ISSUE THREAD

**Issue by 0pLuS0** [loskutov/deadbeef-infobar-ng#2]
Hi,

I noticed you made changes a few days ago, not sure if you're still working on this, to where it still might not compile.

Sorry if I might seem jumpy, that is not my intentions, I only noticed you had done some updating, and I thought to try and compile the source, I just wasn't sure if it was ready, but it has an error and I simply wanted to report it to you is all.

Please see the attached make.log

THANKS

[make.log](https://github.com/loskutov/deadbeef-infobar-ng/files/8401029/make.log)

P.S. This also only compiles a gtk2 version, I ran ```make```.

**Comment by loskutov** [comment]
To compile the gtk3 version, you need to run `make gtk3`.

**Comment by 0pLuS0** [comment]
I just ran ```make``` because that is what was listed in the ``` Readme.md```.

```make gtk3``` compiled.
